# Generated by Django 6.0.5 on 2026-06-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Ho ten')),
                ('ngay_sinh', models.DateField(verbose_name='Ngay sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nu'), ('Khac', 'Khac')], default='Nam', max_length=10, verbose_name='Gioi tinh')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='So dien thoai')),
                ('cccd', models.CharField(blank=True, max_length=20, verbose_name='CCCD/CMND')),
                ('dia_chi', models.CharField(blank=True, max_length=255, verbose_name='Dia chi')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao ho so')),
            ],
            options={
                'verbose_name': 'Khach hang',
                'verbose_name_plural': 'Khach hang',
            },
        ),
        migrations.CreateModel(
            name='LoVacXin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_lo', models.CharField(max_length=50, verbose_name='So lo')),
                ('ngay_nhap', models.DateField(verbose_name='Ngay nhap')),
                ('han_su_dung', models.DateField(verbose_name='Han su dung')),
                ('so_luong_ton', models.IntegerField(default=0, verbose_name='So luong ton')),
            ],
            options={
                'verbose_name': 'Lo vac-xin',
                'verbose_name_plural': 'Kho - Lo vac-xin',
            },
        ),
        migrations.CreateModel(
            name='PhacDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150, verbose_name='Ten phac do')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mo ta')),
                ('doi_tuong', models.CharField(blank=True, max_length=100, verbose_name='Doi tuong ap dung')),
            ],
            options={
                'verbose_name': 'Phac do tiem',
                'verbose_name_plural': 'Phac do tiem',
            },
        ),
        migrations.CreateModel(
            name='VacXin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150, verbose_name='Ten vac-xin')),
                ('phong_benh', models.CharField(max_length=255, verbose_name='Phong benh')),
                ('nha_san_xuat', models.CharField(blank=True, max_length=150, verbose_name='Nha san xuat')),
                ('nuoc_san_xuat', models.CharField(blank=True, max_length=100, verbose_name='Nuoc san xuat')),
                ('do_tuoi_min_thang', models.PositiveIntegerField(default=0, verbose_name='Do tuoi toi thieu (thang)')),
                ('do_tuoi_max_thang', models.PositiveIntegerField(default=1200, verbose_name='Do tuoi toi da (thang)')),
                ('gia', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Gia (VND)')),
            ],
            options={
                'verbose_name': 'Vac-xin',
                'verbose_name_plural': 'Vac-xin',
            },
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_hen', models.DateField(verbose_name='Ngay hen')),
                ('gio_hen', models.TimeField(blank=True, null=True, verbose_name='Gio hen')),
                ('trang_thai', models.CharField(choices=[('cho', 'Cho xac nhan'), ('xacnhan', 'Da xac nhan'), ('datiem', 'Da tiem'), ('huy', 'Da huy')], default='cho', max_length=10, verbose_name='Trang thai')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chu')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='core.khachhang', verbose_name='Khach hang')),
                ('phac_do', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phacdo', verbose_name='Phac do du kien')),
            ],
            options={
                'verbose_name': 'Lich hen',
                'verbose_name_plural': 'Lich hen',
                'ordering': ['-ngay_hen'],
            },
        ),
        migrations.CreateModel(
            name='PhieuSangLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateTimeField(auto_now_add=True, verbose_name='Ngay sang loc')),
                ('nhiet_do', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nhiet do (C)')),
                ('mach', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mach (lan/phut)')),
                ('ket_luan', models.CharField(choices=[('dat', 'Du dieu kien tiem'), ('hoan', 'Hoan tiem'), ('chong', 'Chong chi dinh')], default='dat', max_length=10, verbose_name='Ket luan')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chu')),
                ('bac_si', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bac si sang loc')),
                ('lich_hen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sang_loc', to='core.lichhen', verbose_name='Lich hen')),
            ],
            options={
                'verbose_name': 'Phieu sang loc',
                'verbose_name_plural': 'Phieu sang loc',
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tong tien (VND)')),
                ('phuong_thuc', models.CharField(choices=[('tien_mat', 'Tien mat'), ('chuyen_khoan', 'Chuyen khoan'), ('the', 'Quet the')], default='tien_mat', max_length=15, verbose_name='Phuong thuc')),
                ('ngay_thanh_toan', models.DateTimeField(auto_now_add=True, verbose_name='Ngay thanh toan')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.khachhang', verbose_name='Khach hang')),
                ('lich_hen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lichhen', verbose_name='Lich hen')),
            ],
            options={
                'verbose_name': 'Thanh toan',
                'verbose_name_plural': 'Thanh toan',
            },
        ),
        migrations.CreateModel(
            name='PhacDoChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mui_so', models.PositiveIntegerField(verbose_name='Mui so')),
                ('khoang_cach_ngay', models.PositiveIntegerField(default=0, help_text='Mui 1 = 0. Mui sau = so ngay cach mui lien truoc.', verbose_name='Khoang cach den mui truoc (ngay)')),
                ('phac_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='core.phacdo', verbose_name='Phac do')),
                ('vac_xin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacxin', verbose_name='Vac-xin')),
            ],
            options={
                'verbose_name': 'Chi tiet phac do',
                'verbose_name_plural': 'Chi tiet phac do',
                'ordering': ['phac_do', 'mui_so'],
            },
        ),
        migrations.CreateModel(
            name='MuiTiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mui_so', models.PositiveIntegerField(default=1, verbose_name='Mui so')),
                ('ngay_tiem', models.DateField(verbose_name='Ngay tiem')),
                ('vi_tri_tiem', models.CharField(blank=True, max_length=100, verbose_name='Vi tri tiem')),
                ('ngay_hen_mui_ke', models.DateField(blank=True, null=True, verbose_name='Ngay hen mui ke tiep')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mui_tiem', to='core.khachhang', verbose_name='Khach hang')),
                ('lo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lovacxin', verbose_name='Lo vac-xin')),
                ('nguoi_tiem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi tiem (dieu duong)')),
                ('phac_do', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phacdo', verbose_name='Phac do')),
                ('vac_xin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vacxin', verbose_name='Vac-xin')),
            ],
            options={
                'verbose_name': 'Mui tiem',
                'verbose_name_plural': 'Mui tiem (So tiem)',
                'ordering': ['-ngay_tiem'],
            },
        ),
        migrations.AddField(
            model_name='lovacxin',
            name='vac_xin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo', to='core.vacxin', verbose_name='Vac-xin'),
        ),
    ]
