# Generated by Django 6.0.5 on 2026-06-02 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khach_hang', to=settings.AUTH_USER_MODEL, verbose_name='Tai khoan dang nhap'),
        ),
    ]
