# Generated by Django 6.0.5 on 2026-06-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_khachhang_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phacdo',
            name='nhom',
            field=models.CharField(choices=[('tre_em', 'Tre em'), ('nguoi_lon', 'Nguoi lon')], default='tre_em', max_length=10, verbose_name='Nhom doi tuong'),
        ),
    ]
