# Generated by Django 6.0.5 on 2026-06-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phacdo_nhom'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='bac_si_chi_dinh',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bac si chi dinh'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='benh_vien',
            field=models.CharField(blank=True, max_length=200, verbose_name='Benh vien chi dinh'),
        ),
        migrations.AddField(
            model_name='lichhen',
            name='loai_chi_dinh',
            field=models.CharField(choices=[('khach_hang', 'Mong muon cua khach hang'), ('benh_vien', 'Benh vien chi dinh')], default='khach_hang', max_length=12, verbose_name='Hinh thuc chi dinh'),
        ),
    ]
