# Generated by Django 6.0.5 on 2026-06-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lichhen_bac_si_chi_dinh_lichhen_benh_vien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhen',
            name='loai_chi_dinh',
            field=models.CharField(choices=[('khach_hang', 'Mong muốn của khách hàng'), ('benh_vien', 'Bệnh viện chỉ định')], default='khach_hang', max_length=12, verbose_name='Hinh thuc chi dinh'),
        ),
    ]
