# Generated by Django 6.0.5 on 2026-06-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lichhen_loai_chi_dinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoDoiSauTiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_diem', models.CharField(choices=[('30p', 'Sau 30 phut (tai phong kham)'), ('24h', 'Sau 24 gio'), ('48h', 'Sau 48 gio'), ('khac', 'Khac')], default='30p', max_length=5, verbose_name='Thoi diem theo doi')),
                ('nhiet_do', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Nhiet do (C)')),
                ('trieu_chung', models.CharField(blank=True, help_text='Vd: sot, sung dau cho tiem, quay khoc, phat ban...', max_length=255, verbose_name='Trieu chung')),
                ('muc_do', models.CharField(choices=[('binh_thuong', 'Binh thuong'), ('nhe', 'Phan ung nhe'), ('can_chu_y', 'Can chu y'), ('nghiem_trong', 'Nghiem trong')], default='binh_thuong', max_length=15, verbose_name='Muc do')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chu')),
                ('ngay_ghi_nhan', models.DateTimeField(auto_now_add=True, verbose_name='Ngay ghi nhan')),
                ('mui_tiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theo_doi', to='core.muitiem', verbose_name='Mui tiem')),
            ],
            options={
                'verbose_name': 'Theo doi sau tiem',
                'verbose_name_plural': 'Theo doi sau tiem',
                'ordering': ['-ngay_ghi_nhan'],
            },
        ),
    ]
