# Generated by Django 6.0.5 on 2026-06-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_theodoisautiem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhen',
            name='trang_thai',
            field=models.CharField(choices=[('cho', 'Chờ xác nhận'), ('xacnhan', 'Đã xác nhận'), ('datiem', 'Đã tiêm'), ('huy', 'Đã hủy')], default='cho', max_length=10, verbose_name='Trang thai'),
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(max_length=255, verbose_name='Noi dung')),
                ('duong_dan', models.CharField(blank=True, max_length=200, verbose_name='Duong dan')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Da doc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi nhan')),
            ],
            options={
                'verbose_name': 'Thong bao',
                'verbose_name_plural': 'Thong bao',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
