# Generated by Django 6.0.5 on 2026-06-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lichhen_trang_thai_thongbao'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuyTrinhTiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giai_doan', models.PositiveSmallIntegerField(choices=[(1, 'Cho bac si sang loc'), (2, 'Bac si da xac nhan du dieu kien'), (3, 'Da len don'), (4, 'Da xuat kho'), (5, 'Dieu duong da tiem'), (6, 'Theo doi sau tiem')], default=1, verbose_name='Giai doan')),
                ('ghi_chu_sang_loc', models.CharField(blank=True, max_length=255, verbose_name='Ghi chu sang loc')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Cap nhat')),
                ('lich_hen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quy_trinh', to='core.lichhen', verbose_name='Lich hen')),
                ('lo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lovacxin', verbose_name='Lo xuat kho')),
                ('mui_tiem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.muitiem', verbose_name='Mui tiem')),
                ('vac_xin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vacxin', verbose_name='Vac-xin (don)')),
            ],
            options={
                'verbose_name': 'Quy trinh tiem',
                'verbose_name_plural': 'Quy trinh tiem',
            },
        ),
    ]
