# Generated by Django 6.0.5 on 2026-06-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quytrinhtiem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quytrinhtiem',
            name='thanh_toan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.thanhtoan', verbose_name='Thanh toan'),
        ),
        migrations.AlterField(
            model_name='quytrinhtiem',
            name='giai_doan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Khách đã tới'), (2, 'Khách đang chờ'), (3, 'Đã vào phòng khám'), (4, 'Bác sĩ sàng lọc'), (5, 'Bác sĩ lên đơn'), (6, 'Thanh toán'), (7, 'Xuất kho'), (8, 'Tiêm'), (9, 'Theo dõi sau tiêm'), (10, 'Hoàn tất')], default=1, verbose_name='Giai doan'),
        ),
    ]
