# Generated by Django 6.0.5 on 2026-06-03 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quytrinhtiem_thanh_toan_alter_quytrinhtiem_giai_doan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1, verbose_name='So luong')),
                ('ngay_xuat', models.DateTimeField(auto_now_add=True, verbose_name='Ngay xuat')),
                ('lo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_xuat', to='core.lovacxin', verbose_name='Lo')),
                ('nguoi_xuat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi xuat')),
                ('quy_trinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_xuat', to='core.quytrinhtiem', verbose_name='Quy trinh')),
            ],
            options={
                'verbose_name': 'Phieu xuat kho',
                'verbose_name_plural': 'Phieu xuat kho',
                'ordering': ['-ngay_xuat'],
            },
        ),
    ]
