# Generated by Django 6.0.5 on 2026-06-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_phieuxuatkho'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieusangloc',
            name='huyet_ap',
            field=models.CharField(blank=True, max_length=20, verbose_name='Huyet ap'),
        ),
    ]
