# Generated by Django 6.0.5 on 2026-06-03 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_phieusangloc_huyet_ap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='quan_he',
            field=models.CharField(choices=[('ban_than', 'Bản thân'), ('con', 'Con'), ('vo_chong', 'Vợ/Chồng'), ('bo_me', 'Bố/Mẹ'), ('khac', 'Người thân khác')], default='ban_than', max_length=10, verbose_name='Quan he voi chu tai khoan'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ho_so', to=settings.AUTH_USER_MODEL, verbose_name='Tai khoan quan ly'),
        ),
    ]
