# Generated by Django 6.0.5 on 2026-06-03 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_khachhang_quan_he_alter_khachhang_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuHuyKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1, verbose_name='So luong huy')),
                ('ly_do', models.CharField(choices=[('het_han', 'Hết hạn sử dụng'), ('loi_chat_luong', 'Lỗi chất lượng'), ('vo_hong', 'Vỡ/hỏng/bảo quản sai'), ('khac', 'Khác')], default='het_han', max_length=20, verbose_name='Ly do')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chu')),
                ('ngay_huy', models.DateTimeField(auto_now_add=True, verbose_name='Ngay huy')),
                ('lo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_huy', to='core.lovacxin', verbose_name='Lo')),
                ('nguoi_huy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi huy')),
            ],
            options={
                'verbose_name': 'Phieu huy kho',
                'verbose_name_plural': 'Phieu huy kho',
                'ordering': ['-ngay_huy'],
            },
        ),
    ]
