# Generated by Django 6.0.5 on 2026-06-03 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_phieuhuykho'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='vac_xin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vacxin', verbose_name='Vac-xin dang ky'),
        ),
        migrations.AlterField(
            model_name='lichhen',
            name='phac_do',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phacdo', verbose_name='Goi / Phac do (tuy chon)'),
        ),
        migrations.AlterField(
            model_name='quytrinhtiem',
            name='giai_doan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Khách đã tới'), (2, 'Khách đang chờ'), (3, 'Đã vào phòng khám'), (4, 'Bác sĩ sàng lọc'), (5, 'Thanh toán'), (6, 'Xuất kho'), (7, 'Tiêm'), (8, 'Theo dõi sau tiêm'), (9, 'Hoàn tất')], default=1, verbose_name='Giai doan'),
        ),
    ]
