# Generated by Django 6.0.5 on 2026-06-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lichhen_vac_xin_alter_lichhen_phac_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacxin',
            name='han_dung_thang',
            field=models.PositiveIntegerField(default=24, verbose_name='Tong han dung (thang)'),
        ),
    ]
