# Generated by Django 6.0.5 on 2026-06-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vacxin_han_dung_thang'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieusangloc',
            name='benh_di_truyen',
            field=models.CharField(blank=True, max_length=255, verbose_name='Benh di truyen'),
        ),
        migrations.AddField(
            model_name='phieusangloc',
            name='dang_dung_thuoc',
            field=models.BooleanField(default=False, verbose_name='Dang dung thuoc'),
        ),
        migrations.AddField(
            model_name='phieusangloc',
            name='di_ung',
            field=models.CharField(blank=True, max_length=255, verbose_name='Di ung'),
        ),
        migrations.AddField(
            model_name='phieusangloc',
            name='thuoc_dang_dung',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thuoc dang dung'),
        ),
        migrations.AddField(
            model_name='phieusangloc',
            name='tien_su_benh',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tien su benh'),
        ),
    ]
