# Generated by Django 6.0.5 on 2026-06-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_phieusangloc_benh_di_truyen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieusangloc',
            name='ly_do_hoan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ly do hoan'),
        ),
    ]
