# Generated by Django 6.0.5 on 2026-06-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_phieusangloc_ly_do_hoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieusangloc',
            name='ly_do_chong',
            field=models.CharField(blank=True, choices=[('soc_phan_ve', 'Từng bị sốc phản vệ với vắc-xin/thành phần ở lần tiêm trước'), ('suy_giam_md', 'Suy giảm miễn dịch nặng (với vắc-xin sống)'), ('di_ung_thanh_phan', 'Dị ứng nặng với thành phần của vắc-xin'), ('khac', 'Khác')], max_length=20, verbose_name='Ly do chong chi dinh'),
        ),
        migrations.AddField(
            model_name='phieusangloc',
            name='ly_do_chong_khac',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ly do chong (khac)'),
        ),
    ]
