# Generated by Django 6.0.5 on 2026-06-03 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_phieusangloc_ly_do_chong_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuQuanTri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(max_length=300, verbose_name='Hanh dong')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian')),
                ('nguoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_quan_tri', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi thuc hien')),
            ],
            options={
                'verbose_name': 'Lich su quan tri',
                'verbose_name_plural': 'Lich su quan tri',
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
