# Generated by Django 6.0.5 on 2026-06-04 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lovacxin_nguoi_nhap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCauDatLaiMatKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngay yeu cau')),
                ('da_xu_ly', models.BooleanField(default=False, verbose_name='Da xu ly')),
                ('ngay_xu_ly', models.DateTimeField(blank=True, null=True, verbose_name='Ngay xu ly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_mat_khau', to=settings.AUTH_USER_MODEL, verbose_name='Tai khoan')),
            ],
            options={
                'verbose_name': 'Yeu cau dat lai mat khau',
                'verbose_name_plural': 'Yeu cau dat lai mat khau',
                'ordering': ['da_xu_ly', '-ngay_tao'],
            },
        ),
    ]
