# Generated by Django 6.0.5 on 2026-06-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_yeucaudatlaimatkhau'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeucaudatlaimatkhau',
            name='tu_choi',
            field=models.BooleanField(default=False, verbose_name='Tu choi'),
        ),
    ]
