# Generated by Django 6.0.5 on 2026-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_yeucaudatlaimatkhau_tu_choi'),
    ]

    operations = [
        migrations.AddField(
            model_name='theodoisautiem',
            name='xu_ly',
            field=models.CharField(blank=True, choices=[('quay_lai', 'Quay lại để kiểm tra'), ('binh_thuong', 'Điều kiện bình thường'), ('theo_doi_tiep', 'Theo dõi tiếp'), ('khac', 'Khác')], max_length=20, verbose_name='Huong xu ly'),
        ),
        migrations.AddField(
            model_name='theodoisautiem',
            name='xu_ly_ghi_chu',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ghi chu/ly do xu ly'),
        ),
    ]
