# Generated by Django 6.0.5 on 2026-06-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_theodoisautiem_xu_ly_theodoisautiem_xu_ly_ghi_chu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TinNhanHoTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la_nhan_vien', models.BooleanField(default=False, verbose_name='Nhan vien gui')),
                ('noi_dung', models.TextField(verbose_name='Noi dung')),
                ('ngay', models.DateTimeField(auto_now_add=True, verbose_name='Ngay')),
                ('da_doc', models.BooleanField(default=False, verbose_name='Da doc')),
                ('khach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_ho_tro', to=settings.AUTH_USER_MODEL, verbose_name='Khach (chu hoi thoai)')),
                ('nguoi_gui', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi gui')),
            ],
            options={
                'verbose_name': 'Tin nhan ho tro',
                'verbose_name_plural': 'Tin nhan ho tro',
                'ordering': ['ngay'],
            },
        ),
    ]
