# Generated by Django 6.0.5 on 2026-06-08 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_thanhtoan_nguoi_thu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phieuxuatkho',
            name='ngay_nhan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngay nhan'),
        ),
        migrations.AddField(
            model_name='phieuxuatkho',
            name='nguoi_nhan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dieu duong nhan'),
        ),
    ]
