# Generated by Django 6.0.5 on 2026-06-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_phieuxuatkho_ngay_nhan_phieuxuatkho_nguoi_nhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovacxin',
            name='ngay_san_xuat',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay san xuat'),
        ),
    ]
